### ISSUE TITLE
TerriaJS can't display velocity from sci-wms

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#100]
I don't know whether this is a TerriaJS problem or a sci-wms problem, but when I drop the endpoint
http://sci-wms.whoi.edu/wms/datasets/sgridtest?REQUEST=GetCapabilities
into http://dev.tampabaymap.org (using the "+Add data" button), TerraJS issues GetMap requests like this that fail with 500 errors:

http://sci-wms.whoi.edu/wms/datasets/sgridtest?time=2015-04-30T04%3A00%3A00Z&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=u%2Cv&bbox=-8453323.832114212%2C2504688.542848654%2C-8140237.7642581295%2C2817774.6107047386&width=256&height=256

**Comment by kwilcox** [comment]
You can fix by setting a default style for the `u,v` layer.

**Comment by rsignell-usgs** [comment]
sci-wms should have set a default style, right?

**Comment by kwilcox** [comment]
Yeah I just meant as a temporary workaround until I got around to fixing the actual bug. Its fixed now if you pull `master`

**Comment by rsignell-usgs** [comment]
Okay, it displays now, but is there a way we could make the default rendering look a little better?
![2015-11-03_18-19-41](https://cloud.githubusercontent.com/assets/1872600/10924845/be8e08a8-8257-11e5-8a2b-cbfedbe5f873.jpg)

**Comment by rsignell-usgs** [comment]
Perhaps we could do like ncWMS does as default: plots vectors all the same length, but with different colors?

**Comment by rsignell-usgs** [comment]
Just a note that with VECTORSCALE specified, things are working nicely with terriaJS: https://github.com/sci-wms/sci-wms/issues/102#issuecomment-154457792

It would be nice to offer the ncWMS-type fixed-size-vectors-with-speed-colored-as-background style perhaps as a default, as in: 

http://hfrnet.ucsd.edu/thredds/wms/HFR/USEGC/2km/hourly/RTV/HFRADAR,_US_East_and_Gulf_Coast,_2km_Resolution,_Hourly_RTV_best.ncd?LAYERS=surface_sea_water_velocity&ELEVATION=0&TIME=2015-11-09T00%3A00%3A00.000Z&TRANSPARENT=true&STYLES=vector%2Frainbow&CRS=EPSG%3A4326&COLORSCALERANGE=0%2C0.5&NUMCOLORBANDS=20&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&SRS=EPSG%3A4326&BBOX=-84.074227766406,26.577358803568,-82.203770718076,28.038653372578&WIDTH=768&HEIGHT=600
