### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by metanomy** [sci-wms/sci-wms#102]
1. Added WFS FVCOM layer to sci-wms: http://crow.marine.usf.edu:8080/thredds/dodsC/FVCOM-Nowcast-Agg.nc.html
2. Attempt to access eastward_sea_water_velocity (http://dev.tampabaymap.org)

![image](https://cloud.githubusercontent.com/assets/11446338/10999719/9fb5eb6a-846b-11e5-844a-22f5578938d0.png)

Error from sci-wms log (docker logs sci-wms):

ERROR:django.request:Internal Server Error: /wms/datasets/wfsfvcom
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/opt/conda/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/opt/conda/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, _args, *_kwargs)
  File "/srv/sci-wms/wms/views.py", line 263, in get
    request = enhance_getmap_request(dataset, layer, request)
  File "/srv/sci-wms/wms/views.py", line 122, in enhance_getmap_request
    colormap=wms_handler.get_colormap(request),
  File "/srv/sci-wms/wms/wms_handler.py", line 195, in get_colormap
    requested_cm = request.GET.get(parameter).split(',')[0].split('_')[1]
IndexError: list index out of range
ERROR:tornado.access:500 GET /wms/datasets/wfsfvcom?time=2013-12-05T07%3A00%3A00Z&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=u&bbox=-20037508.342789244%2C0%2C0%2C20037508.342789244&width=256&height=256 (172.17.42.1) 12.70ms

**Comment by rsignell-usgs** [comment]
Are you using the latest sci-wms from master?
What Opendap link is this hitting?
I can try it on my sci-wms and see if it's just a version issue.

**Comment by metanomy** [comment]
Add this to your sci-wms: http://crow.marine.usf.edu:8080/thredds/dodsC/FVCOM-Nowcast-Agg.nc.html

**Comment by metanomy** [comment]
I can see the data on the sci-wms Leaflet preview, but when I try to access through TerriaJS, that's when it throws the error.

**Comment by rsignell-usgs** [comment]
Try upgrading to the latest sci-wms version.  This works for me, using this json:

```
{
    "catalog": [
        {
          "name": "USF_FVCOM",
          "type": "group",
          "items": [
            {
              "name": "FVCOM Velocity",
              "type": "wms",
              "url": "http://sci-wms.whoi.edu/wms/datasets/usf_fvcom",
              "description": "...",
              "abstract": "Surface elocity vectors from FVCOM",
              "layers": "u,v",
              "getFeatureInfoAsGeoJson": false,
              "parameters": {
                "VECTORSCALE": "4.0",
                "FORMAT": "image/png",
                "STYLES": "vectors_jet",
                "VERSION": "1.1.1",
                "ELEVATION": "0.0"
              }
            }
          ]
        }
    ]
}
```

![2015-11-06_11-22-29](https://cloud.githubusercontent.com/assets/1872600/11002104/d896571e-8478-11e5-9a9d-2e16c89f69ba.jpg)

**Comment by rsignell-usgs** [comment]
@metanomy , okay to close?
