### ISSUE TITLE
External database option

### ISSUE THREAD

**Issue by metanomy** [sci-wms/sci-wms#104]
It would be ideal to be able to store configuration and other data in a separate database. This would allow for better production uses (especially when using Docker). The result would be one container for the data, the other for the web app and logic. Updating the code would simply mean rebuilding one docker container, without having to migrate the data.

**Comment by kwilcox** [comment]
This is already possible, see the Docker section of the documentation

**Comment by metanomy** [comment]
:-1: for my failure to RTFM.
