### ISSUE TITLE
Support COLORBARONLY parameter in GetLegendGraphic requests

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#106]
This is the sneaky way Godiva2 produces legends with the correct range, and would be a way to solve this issue:
https://github.com/TerriaJS/terriajs/issues/774#issuecomment-155089391

So I'm suggesting that it would be nice if this request:
http://sci-wms.whoi.edu/wms/datasets/usf_fvcom?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image/png&layer=salinity&WIDTH=120&HEIGHT=240&COLORBARONLY=true

returned the colorscale graphic _without_ labels.

**Comment by rsignell-usgs** [comment]
Just out of curiosity, I looked at what request the [USGS CMG Portal](http://cmgdata.usgsportals.net/#module-metadata/36c04d9b-c88e-3322-9bdf-bd4d727e10ed/7ef31290-07e7-414f-97b9-4726b4a2ed1d) client is making for legends, and it's making requests like this:

http://pdx.axiomalaska.com/ncWMS/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&STRICT=false&TRANSPARENT=true&LAYER=NDFD_Aggregate/Dew_point_temperature&HORIZONTAL=true&SHOWLABEL=false&STYLE=boxfill/rainbow&PALETTE=rainbow&COLORSCALERANGE=3.85278,22.40834&LOGSCALE=false

and gets custom limits by also supplying the `COLORSCALERANGE` parameter (and having the server understand it) which is another way of accomplishing the same goal.

**Comment by kwilcox** [comment]
I'm assuming the title is incorrect and you mean `COLORBARONLY`?

**Comment by kwilcox** [comment]
Specifying the `COLORSCALERANGE` in the GetLegendGraphic request is a much better way to accomplish this.

We already support hiding the "values", see: http://sci-wms.github.io/sci-wms/docs/advanced.html#wms-extensions

**Comment by rsignell-usgs** [comment]
@kwilcox, okay, I agree the `COLORSCALERANGE` is the right way to do this.  

So now I think the only thing I'm requesting is that we translate the request `COLORBARONLY=True` into `SHOWLABEL=False`, `SHOWVALUES=False`
