### ISSUE TITLE
Can we enable CORS with the docker installer?

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#109]
Can the docker installation be configured so that someone who installs sci-wms using docker has CORS enabled?

**Comment by rsignell-usgs** [comment]
@kwilcox gchatted me: "if someone needs CORS, they have to do it on their end
its really a pita to get it in at the application level.   CORS is an nginx thing, its up to the server"

**Comment by kwilcox** [comment]
I'd rather not configure CORS inside of `sci-wms`. It is up to the organization hosting `sci-wms` to decide how to setup their own CORS permissions. If they need CORS, they can enable it though nginx or apache.
