### ISSUE TITLE
TypeError: len() of unsized object

### ISSUE THREAD

**Issue by metanomy** [sci-wms/sci-wms#110]
Attempting to u,v from this layer: http://dev.tampabaymap.org:7002/wms/datasets/wfsfvcom?REQUEST=GetCapabilities

ERROR:tornado.access:500 GET /wms/datasets/wfsfvcom?time=2015-12-15T06%3A00%3A00Z&vectorscale=1.0&styles=vectors_jet&version=1.1.1&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&tiled=true&feature_count=101&service=WMS&request=GetMap&layers=u%2Cv&bbox=-9196903.243272407%2C3130860.6785608195%2C-9157767.484790396%2C3169996.4370428286&width=256&height=256 (172.17.0.1) 124.93ms
ERROR:django.request:Internal Server Error: /wms/datasets/wfsfvcom
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, _args, *_kwargs)
  File "/srv/sci-wms/wms/views.py", line 292, in get
    response = getattr(dataset, reqtype.lower())(layer, request)
  File "/srv/sci-wms/wms/models/datasets/ugrid.py", line 255, in getmap
    if (len(spatial_idx) == 0) or (len(face_indicies_spatial_idx) == 0):
TypeError: len() of unsized object

**Comment by kwilcox** [comment]
I believe this is fixed in `master`, let me cut a `1.5.0` release so you can test that

**Comment by metanomy** [comment]
Awesome, thanks!

**Comment by kwilcox** [comment]
I just confirmed that this is fixed. You should see some fairly significant speedups on vector layers with `1.5.0`.

You can pull the new `latest` image now: `docker pull axiom/sci-wms` and restart your container

**Comment by metanomy** [comment]
Thanks for the quick turn-around, the performance increase is notable!
