### ISSUE TITLE
'SGridDataset' object has no attribute 'describelayer'

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#112]
This `DescribeLayer` request from TerriaJS: 
http://sci-wms.whoi.edu/wms/datasets/use_fmrc_coawst_4_use_best?service=WMS&version=1.1.1&sld_version=1.1.0&request=DescribeLayer&layers=u%2Cv
is producing:

```
 'SGridDataset' object has no attribute 'describelayer'
```

I'm trying to display vectors from sci-wms COAWST (sgrid) endpoint, via this URL:
http://comt.sura.org/proxy_3001/#https://rawgit.com/rsignell-usgs/ehzrap/master/testing/coawst.json

Would it be difficult to add a simple describelayer capability?

**Comment by kwilcox** [comment]
I don't know what TerriaJS is doing... probably just checking for SLD support in the WMS server you give it.  `sci-wms` isn't an SLD enabled WMS, so adding this wouldn't do anything.  Adding SLD support would be... very hard.

```
7.4 DescribeLayer (SLD WMS only)
The optional DescribeLayer operation applies only to a Styled Layer Descriptor WMS.
See the SLD specification [3] for this operation. 
```
