### ISSUE TITLE
Why isn't the colorscalerange request working here?

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#115]
I added this OpenDAP COMT ADCIRC dataset to my sci-wms instance:
http://comt.sura.org/thredds/dodsC/data/comt_1_archive/inundation_tropical/UND_ADCIRC/Hurricane_Ike_2D_final_run_with_waves

and everything seemed to go okay.  But when I do `GetMap` requests, it seems to ignore the `colorscalerange` request.    Changing it to  `[0,5]` to `[0,2]` or `[0,50]` in the request below has no effect:

http://sci-wms.whoi.edu/wms/datasets/adcirc_ike_2d_waves?time=2008-09-13T06%3A00%3A00Z&colorscalerange=0.00%2C5.00&numcontours=40&styles=filledcontours_jet&version=1.1.1&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&tiled=true&feature_count=101&service=WMS&request=GetMap&layers=zeta&bbox=-10801469.341034826%2C3287403.71248886%2C-10644926.307106785%2C3443946.746416902&width=256&height=256

It always just produces this image:
![foo](https://cloud.githubusercontent.com/assets/1872600/13494969/b48ef96c-e115-11e5-9aef-ff3df463cebe.png)

It should look like this:
![2016-03-03_7-56-48](https://cloud.githubusercontent.com/assets/1872600/13494986/e5b214ca-e115-11e5-97b2-4f9614438d4e.png)

**Comment by rsignell-usgs** [comment]
These two WMS requests have different `colorscalerange`, but give the same response:

https://gamone.whoi.edu/wms/datasets/ec2015?time=2000-01-01T00%3A00%3A00Z&version=1.3.0&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&feature_count=101&colorscalerange=0,1&service=WMS&request=GetMap&layers=Amp&bbox=-7514065.628545966%2C5400734.670517413%2C-7435794.111581946%2C5479006.187481433&width=256&height=256

https://gamone.whoi.edu/wms/datasets/ec2015?time=2000-01-01T00%3A00%3A00Z&version=1.3.0&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&feature_count=101&colorscalerange=0,5&service=WMS&request=GetMap&layers=Amp&bbox=-7514065.628545966%2C5400734.670517413%2C-7435794.111581946%2C5479006.187481433&width=256&height=256

**Comment by rsignell-usgs** [comment]
@kwilcox, sci-wms is kicking arse here on the 2M+, 3M+ mesh:
![2018-03-23_17-35-09](https://user-images.githubusercontent.com/1872600/37854299-a68f2f76-2ec0-11e8-810d-77090fc275df.jpg)
https://gamone.whoi.edu/terriamap/#clean&proxy/_60s/https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/ec2015.json
but as you can see it's totally ignoring the colorscalerange requests on the getmap requests (the m2 amplitude is more than 1m in the Gulf of Maine)   Why?

**Comment by brianmckenna** [comment]
@rsignell-usgs looks like we have an issue parsing zero (int or float), must be evaluated as a truth value somewhere. Set lower limit to 0.01 and I believe it works.

Peeking around the code, it's been a while.

**Comment by brianmckenna** [comment]
this will do it...

https://github.com/sci-wms/sci-wms/blob/master/wms/mpl_handler.py#L138

Checking for any other places this might be the case and I can update

**Comment by rsignell-usgs** [comment]
@brianmckenna , wow, I never would have figured that out.   Thanks!

https://gamone.whoi.edu/wms/datasets/ec2015?time=2000-01-01T00%3A00%3A00Z&version=1.3.0&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&feature_count=101&colorscalerange=0,1&service=WMS&request=GetMap&layers=Amp&bbox=-7514065.628545966%2C5400734.670517413%2C-7435794.111581946%2C5479006.187481433&width=256&height=256

https://gamone.whoi.edu/wms/datasets/ec2015?time=2000-01-01T00%3A00%3A00Z&version=1.3.0&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&feature_count=101&colorscalerange=0.01,1&service=WMS&request=GetMap&layers=Amp&bbox=-7514065.628545966%2C5400734.670517413%2C-7435794.111581946%2C5479006.187481433&width=256&height=256

**Comment by rsignell-usgs** [comment]
Guys, I'm still struggling to figure out what is going on with the colorscalerange. 
This request is for M2 amplitude in the Cape Cod region.   The amplitude should be something like 1.2 meters in Cape Cod Bay, but if I request a colorscale of 0.01,1 I get nearly all blue.  I need to specify 0.01,0.4 to get something that shows some range:

https://gamone.whoi.edu/wms/datasets/ec2015?time=2000-01-01T00%3A00%3A00Z&version=1.1.1&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&feature_count=101&service=WMS&request=GetMap&layers=Amp&bbox=-8140237.7642581295%2C5009377.085697312%2C-7827151.696402049%2C5322463.153553393&width=256&height=256&colorscalerange=0.01,0.4

![ec2015](https://user-images.githubusercontent.com/1872600/38167218-c1216a76-34ff-11e8-8d32-27c992239a70.png)


Is there a chance that the map is autoscaling first to the total range of the data, then the colorscalerange is specifying a fraction of that range?    Something like that might explain it.   I'm really going crazy here trying to figure this out!!!

**Comment by rsignell-usgs** [comment]
Okay, red herring here.  The problem is actually with the time specification.  Raised in #127.
