### ISSUE TITLE
Where is the source for the documentation

### ISSUE THREAD

**Issue by cbcunc** [sci-wms/sci-wms#118]
Where is the source for http://sci-wms.github.io/sci-wms/ so I can fork it and make a pull request?

**Comment by daf** [comment]
@cbcunc I think it's using the traditional approach for github pages, an "orphaned" gh-pages branch: https://github.com/sci-wms/sci-wms/tree/gh-pages

**Comment by cbcunc** [comment]
Ah, thanks.
