### ISSUE TITLE
UGRID nc files for development

### ISSUE THREAD

**Issue by ayan-usgs** [sci-wms/sci-wms#12]
It would great to have a few netCDF datasets that were UGRID compliant. This would provide concrete UGRID to develop and test against.

**Comment by rsignell-usgs** [comment]
Here are (hopefully) UGRID compliant OPeNDAP Data URLS from 3 different ocean forecast models:
http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc
http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic
http://amb6400b.stccmop.org:8080/thredds/dodsC/model_data/forecast
