### ISSUE TITLE
Problems Displaying Test Data

### ISSUE THREAD

**Issue by cbcunc** [sci-wms/sci-wms#120]
I deployed a sci-wms docker container according to the [instructions](http://sci-wms.github.io/sci-wms/docs/deployment.html#docker-recommended). I can view the landing page. I can login. I can update the UgridTest and SgridTest datasets. I can view the schemas for the datasets using the /show links. The GetCapabilities links work. When I go to the leaflet demo, I can click on the dataset layers and see the active layers. If I click on an active layer, however, to see it (in this case, SST) on the leaflet map, nothing appears on the map. I'm trying to verify that the sci-wms instance in the docker container works before expending a lot of effort adding datasets.

The log file has entries after that last step (prior to which there were none):

> [2017-01-31 12:17:25,342: WARNING/MainProcess] No triangles in field of view, returning empty tile.
[2017-01-31 12:17:25,493: WARNING/MainProcess] No triangles in field of view, returning empty tile.
[2017-01-31 12:17:25,516: WARNING/MainProcess] No triangles in field of view, returning empty tile.
[2017-01-31 12:17:25,526: WARNING/MainProcess] No triangles in field of view, returning empty tile.
[2017-01-31 12:17:25,533: WARNING/MainProcess] No triangles in field of view, returning empty tile.
[2017-01-31 12:17:25,668: WARNING/MainProcess] No triangles in field of view, returning empty tile.
[2017-01-31 12:17:25,750: WARNING/MainProcess] No triangles in field of view, returning empty tile.

The standard output contains py.warnings with a bit more information:

> pylantic:Docker cbc$ docker run --rm -it -p 7002:7002 -v /Users/cbc/sciwms/db:/srv/sci-wms/sciwms/db/ axiom/sci-wms
Sourcing profile...
Migrating sci-wms...
Operations to perform:
  Synchronize unmigrated apps: staticfiles, rest_framework, wmsrest, admindocs, grappelli, messages
  Apply all migrations: auth, sessions, sites, contenttypes, admin, wms
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying wms.0001_initial... OK
  Applying wms.0002_auto_20150302_1106... OK
  Applying wms.0003_auto_20150302_1510... OK
  Applying wms.0004_auto_20150310_0955... OK
  Applying wms.0005_layer... OK
  Applying wms.0006_auto_20150424_1058... OK
  Applying wms.0007_auto_20150424_1604... OK
  Applying wms.0008_auto_20150428_2136... OK
  Applying wms.0009_auto_20150428_2030... OK
  Applying wms.0010_auto_20150428_2201... OK
  Applying wms.0011_auto_20150428_2211... OK
  Applying wms.0012_layer_default_max... OK
  Applying wms.0013_layer_default_min... OK
  Applying wms.0014_auto_20150428_2247... OK
  Applying wms.0015_change_testing_datasets... OK
  Applying wms.0016_layer_std_name... OK
  Applying wms.0017_create_layers... OK
  Applying wms.0018_add_style_to_virtuallayers... OK
  Applying wms.0019_remove_virtuallayer... OK
  Applying wms.0020_add_back_virtuallayer... OK
  Applying wms.0021_auto_20150429_1429... OK
  Applying wms.0022_auto_20150429_1533... OK
  Applying wms.0023_auto_20150501_1427... OK
  Applying wms.0024_auto_20150501_1731... OK
  Applying wms.0025_auto_20150504_1143... OK
  Applying wms.0026_dataset_slug... OK
  Applying wms.0027_auto_20150602_1603... OK
  Applying wms.0028_auto_20150710_1637... OK
  Applying wms.0029_auto_20150716_1639... OK
  Applying wms.0030_auto_20150716_1648... OK
  Applying wms.0031_auto_20151029_1205... OK
  Applying wms.0032_auto_20151030_1031... OK
  Applying wms.0033_auto_20151030_1103... OK
  Applying wms.0034_auto_20151030_1140... OK
Collecting sci-wms static assets...
========================================================================
sci-wms user:         "sciwmsuser"
sci-wms password:     "mIe4x93haf2wRtg8"
========================================================================
Starting sci-wms...
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "
WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "
WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "
WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "
WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):
WARNING:wms:No triangles in field of view, returning empty tile.

**Comment by kwilcox** [comment]
I believe one of the test cases is in the Columbia River. Do you see anything if you zoom into Washington/Oregon?

**Comment by cbcunc** [comment]
Yes, thank you. I should have been able to tell that from looking at selfe_ugrid.nc. I was thrown because the last time I looked at this is was a tiny area in the St. Lawrence.

**Comment by cbcunc** [comment]
On my next documentation PR, I may note this.
