### ISSUE TITLE
Docker Build Failure/requirements.txt fails conda install

### ISSUE THREAD

**Issue by cbcunc** [sci-wms/sci-wms#122]
In pursuit of testing a suggested change to documentation in #119 (changing ioos channel to conda-forge) and attempting a fix to #121 (by adding a make migrations step fo the Dockerfile), I found that the Dockerfile will not build, due to a failure to install requirements.txt. jsonfield==1.0.3 is not available in conda-forge, although I do find it in @ocefpaf's channel. Adding that channel, djangorestframework==3.2.4 is not available in any channel. Changing the djangorestframewotk requirement to unpinned results in django-typed-models==0.5.0 being not found. Fixing that by changing the ioos channel to conda-forge (as suggested in #119) finds django-typed-models==0.5.0 but the conda install of requirements.txt times out resolving dependencies, resulting in a "Killed" message from docker build (and a hung process if done natively on Debian Jesse outside of docker build with the version of Miniconda3 prescribed in the Dockerfile):

```
Step 8/22 : RUN conda install --channel conda-forge --channel ocefpaf --file /tmp/requirements.txt
 ---> Running in 7e5a8c950c2b
Fetching package metadata: ........
Solving package specifications: .........Killed
```

**Comment by ocefpaf** [comment]
Somehow I never saw this message! Sorry @cbcunc!!

I believe that I moved everything from my channel to `conda-forge`. If not, I'm reviving sci-wms Dockerfile and Travis-CI today and I'll add them.
