### ISSUE TITLE
Installation/Deployment testing

### ISSUE THREAD

**Issue by drf5n** [sci-wms/sci-wms#123]
On http://sci-wms.github.io/sci-wms/docs/deployment.html or http://sci-wms.github.io/sci-wms/docs/installation.html there should be a section for testing the deployment.

In writing this issue, I discovered these might be reasonable quick tests:

    # see webserver response
    curl http://locahost:7002  # see webserver home page
    # see sample GetCapabilities doc
    curl http://localhost:7002/wms/datasets/ugridtest?REQUEST=GetCapabilities

I'm not attached to these tests, but it would be useful to point people towards the working end result.

**Comment by kwilcox** [comment]
New documentation in 2.0.0 (coming soon) fixes this, thanks
