### ISSUE TITLE
problem with time specification in GetCapabilities?

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#127]
For some reason, even though the getcaps https://gamone.whoi.edu/wms/datasets/f53?REQUEST=GetCapabilities returns
```
<Extent name="time">2000-01-01T00:00:00/2000-02-06T00:00:00/P1D</Extent>
```
 if I specify `2000-01-0100:00:00Z` I get the **2nd* time step instead of the desired 1st time step.

This must be some time zone thing, but it's strange.   By trial and error with getMap requests, I discovered that the change from 1st time step (M2) to the 2nd time step (S2) happens from `1999-12-31T11:00:00Z` to `1999-12-31T12:00:00Z`.  Does that make any sense?

Could this be because the sciwms `getCapabilities` is not specifying a `Z` on the end of the extent?

I notice that in other `getCapabilities` like ncwms that times in the extent are specified with `Z` at the end, like:
```
<Extent name="time" >2013-01-03T01:00:00.000Z/2013-01-05T00:00:00.000Z/PT1H </Extent>
```
but this would mean that some if the `Z` isn't supplied, the dateline is assumed, right?

Here's the evidence that is shifts from 1st to 2nd step between 11am and 12am on Dec 31.

https://gamone.whoi.edu/wms/datasets/f53?time=1999-12-31T11%3A00%3A00Z&version=1.1.1&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&feature_count=101&service=WMS&request=GetMap&layers=Amp&bbox=-8140237.7642581295%2C5009377.085697312%2C-7827151.696402049%2C5322463.153553393&width=256&height=256&colorscalerange=0.01,2.0

![ec2015 1](https://user-images.githubusercontent.com/1872600/38167394-61555f82-3502-11e8-9f0f-6e93818f2409.png)

https://gamone.whoi.edu/wms/datasets/f53?time=1999-12-31T12%3A00%3A00Z&version=1.1.1&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&feature_count=101&service=WMS&request=GetMap&layers=Amp&bbox=-8140237.7642581295%2C5009377.085697312%2C-7827151.696402049%2C5322463.153553393&width=256&height=256&colorscalerange=0.01,2.0

![ec2015 2](https://user-images.githubusercontent.com/1872600/38167396-675531a0-3502-11e8-98bd-1a5b49356caa.png)

**Comment by kwilcox** [comment]
The links above don't work because there is no variable named `Amp`. What is the variable name I should be trying to reproduce with?

**Comment by rsignell-usgs** [comment]
https://gamone.whoi.edu/wms/datasets/ec2015?time=2000-02-06T00%3A00%3A00Z&version=1.1.1&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&feature_count=101&colorscalerange=0.01%2C2&service=WMS&request=GetMap&layers=M2_Amp&bbox=-8140237.7642581295%2C5009377.085697312%2C-7827151.696402049%2C5322463.153553393&width=256&height=256

**Comment by kwilcox** [comment]
I believe this is solved here:  https://github.com/sci-wms/sci-wms/pull/131/commits/381e06fe2822077230308f880c68eea815c6d095

We were bisecting right and returning the "right" (as in direction) for WMS time parameters that matched a time value in the netCDF.

**Comment by rsignell-usgs** [comment]
I will test when the new docker container becomes available.

**Comment by rsignell-usgs** [comment]
Indeed, this is now fixed!   Requesting the start time indeed gives the 1st value:

https://gamone.whoi.edu/wms/datasets/f53?time=2000-01-01T00:00Z&version=1.1.1&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&feature_count=101&service=WMS&request=GetMap&layers=Amp&bbox=-8140237.7642581295%2C5009377.085697312%2C-7827151.696402049%2C5322463.153553393&width=256&height=256&colorscalerange=0.0,2.0

produces
![f53](https://user-images.githubusercontent.com/1872600/38361652-212f0578-389c-11e8-98a6-55341887bddf.png)
