### ISSUE TITLE
SGRID compliant files for development

### ISSUE THREAD

**Issue by ayan-usgs** [sci-wms/sci-wms#13]
SGRID files compliant with Bert's proposed [SGRID conventions](http://bit.ly/sgrid_cf) should be provided so that there is something to develop against.

**Comment by rsignell-usgs** [comment]
I modified the `NcML` for this dataset to be what I believe to be SGRID compliant:
http://geoport.whoi.edu/thredds/dodsC/coawst_4/use/fmrc/coawst_4_use_best.ncd.html

One question is whether we are going to require `grid` and `location` attributes for every variable in an SGRID dataset.   I think we should have the default be that if not specified, we use the regular CF conventions.  In other words, we would NOT require that every variable that is at the grid cell center specify:

```
grid='grid'
location='face'
```

One issue with this example SGRID compliant dataset is that my specification of "CF-1.6, SGRID-0.1" is getting screwed up by THREDDS.   So if we are using an SGRID convention attribute to determine whether we've got SGRID files, it will fail here.  I've raised on issue here:
https://github.com/Unidata/thredds/issues/104

**Comment by kwilcox** [comment]
Are there ultimate plans for a `pysgrid` library similar to that of `pyugrid`?

**Comment by ayan-usgs** [comment]
Yes, I am leaning towards writing a pysgrid library that sci-wms (and others) can use.

**Comment by kwilcox** [comment]
@ayan-usgs did you get the datasets you needed for testing?

**Comment by ayan-usgs** [comment]
@kwilcox,

Yes, I have some test files. I'll close this issue.
