### ISSUE TITLE
'UGridDataset' object has no attribute 'describelayer'

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#133]
This request should work:

https://gamone.whoi.edu/wms/datasets/ec2015?service=WMS&version=1.1.1&sld_version=1.1.0&request=DescribeLayer&layers=K1_Amp

but gives the error:
'UGridDataset' object has no attribute 'describelayer'

**Comment by kwilcox** [comment]
It isn't required by the WMS spec and is only meant for servers that support SLD (of which `sci-wms` does not)...

**Comment by rsignell-usgs** [comment]
Okay, I now understand that `describeLayer` is for WCS and WFS layers, not WMS, so closing.
