### ISSUE TITLE
Provide at least one GetFeatureInfo type TerriaJS can read

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#134]
It seems like at one point `getFeatureInfo` was working for UGRID:
https://github.com/axiom-data-science/sci-wms/commit/8f00238f4a481d1d3fa0f77a1cbebed85a68b384

but when you click a location here:
https://gamone.whoi.edu/terriamap/#clean&proxy/_60s/https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/ec2015.json
you get "Feature Information: no data is available here", which means the `getFeatureInfo` is not working, right?
![2018-04-05_8-57-25](https://user-images.githubusercontent.com/1872600/38366986-79e8d528-38af-11e8-8008-a0349391ff22.png)

**Comment by kwilcox** [comment]
I don't even see TerriaJS making GFI calls to sci-wms, it must be failling somewhere before that (maybe because DescribeLayer doesn't return?)

**Comment by rsignell-usgs** [comment]
@kring, does TerriaJS need the `describeLayer` request to be successful in order for the `getFeatureInfo` request to be issued?

**Comment by kring** [comment]
@rsignell-usgs no, it only uses `DescribeLayer` to find a corresponding WCS or WFS server, if there is one. GetFeatureInfo should work even if `DescribeLayer` doesn't exist or returns an error.

Looks like the problem here is that the WMS server doesn't advertise any `GetFeatureInfoFormat` formats that TerriaJS supports.  Here's the list from `GetCapabilities` (https://gamone.whoi.edu/wms/datasets/ec2015?service=WMS&request=GetCapabilities):
![image](https://user-images.githubusercontent.com/924374/38405964-097c7670-39b6-11e8-9fc4-adc597fbd90a.png)

TerriaJS / Cesium support the following formats out of the box:
* `application/json`
* `text/xml`
* `text/html`

**Comment by rsignell-usgs** [comment]
@kring, thanks so much, seems like is should be pretty easy for us to support one of these!

**Comment by kwilcox** [comment]
@rsignell-usgs check 2.0 for this now please

**Comment by rsignell-usgs** [comment]
@kwilcox and @kring, I see how that the [GetCapabilities of sci-wms 2.0](https://js-169-194.jetstream-cloud.org/wms/datasets/ec2015_power?service=WMS&version=1.3.0&request=GetCapabilities) now contains `text/html` which is supported by TerriaJS:
```
<GetFeatureInfo>
<Format>text/csv</Format>
<Format>text/tsv</Format>
<Format>application/json</Format>
<Format>text/html</Format>
```
but unfortunately `getFeatureInfo` is still not working.    Loading up a dataset like:
https://maps.usgs.gov/terriamap/#share=g-054e79f46de35986c3d321ab60340662
and clicking on the map results in queries like:

https://maps.usgs.gov/terriamap/proxy/https://js-169-194.jetstream-cloud.org/wms/datasets/ec2015_power?version=1.1.1&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&feature_count=101&colorscalerange=0%2C0.2&service=WMS&request=GetFeatureInfo&layers=O1_Amp&bbox=-8766409.899970295%2C2504688.542848654%2C-7514065.628545966%2C3757032.814272983&width=256&height=256&query_layers=O1_Amp&x=8&y=165&info_format=text%2Fhtml

and when issued from the brower URL:

https://js-169-194.jetstream-cloud.org/wms/datasets/ec2015_power?version=1.1.1&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&feature_count=101&colorscalerange=0%2C0.2&service=WMS&request=GetFeatureInfo&layers=O1_Amp&bbox=-8766409.899970295%2C2504688.542848654%2C-7514065.628545966%2C3757032.814272983&width=256&height=256&query_layers=O1_Amp&x=8&y=165&info_format=text%2Fhtml

returns:
```
No cells in the node tree for point -78.3984375, 25.601902261115715
```
![2018-08-02_19-44-43](https://user-images.githubusercontent.com/1872600/43616821-97265bfc-968c-11e8-8540-40dae3f8c612.jpg)

**Comment by rsignell-usgs** [comment]
@kwilcox , I just wanted to report that this is still a problem, and we really need this feature for the USGS total water level project.  Here's an working example of what doesn't work:
https://gamone.whoi.edu/terriamap/#share=g-b2b88419e0335d9f8fc60d14f5910924

![clipboard02](https://user-images.githubusercontent.com/1872600/47566081-90f0f680-d8f8-11e8-9c58-e460ae2ccd09.png)

**Comment by kwilcox** [comment]
Fixed here: https://github.com/sci-wms/sci-wms/commit/42e8169320963214a6b1099c01aa79556813a111
