### ISSUE TITLE
Sandy Adcirc ASGS datasets failing on sci-wms 2.0

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#136]
Most UGRID datasets I added worked fine with sci-wms 2.0 worked fine, but the Sandy ASGS ADCIRC datasets that used to work on sci-wms are now failing on sci-wms 2.0.

An example dataset is:
http://opendap.renci.org:1935/thredds/catalog/ASGS/sandy/25/nc6b/blueridge.renci.org/ncfs/nhcConsensus/catalog.html?dataset=ASGSTCResults2/sandy/25/nc6b/blueridge.renci.org/ncfs/nhcConsensus/00_dir.ncml

And when I try adding the DAP url:
http://opendap.renci.org:1935/thredds/dodsC/ASGS/sandy/25/nc6b/blueridge.renci.org/ncfs/nhcConsensus/00_dir.ncml
via the sci-wms datasets interface, I get:
```
Status: MISSING
```

**Comment by kwilcox** [comment]
This is working locally for me, I believe it is due to a worker timeout when updating the topology cache.

**Comment by kwilcox** [comment]
![selection_033](https://user-images.githubusercontent.com/13939/38741820-dafed2ae-3f08-11e8-990c-e82a3fcabfc9.png)
