### ISSUE TITLE
Negative values missing in the SGRID test case!

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#137]
This is truly bizarre, and I don't know if this has always been there or just cropped up in v2.0, but I just looked at the u velocity component from the provided sample SGRID dataset, with color scaling from -1 to 1, and with the "jet" colormap, and as you can see from the distinct lack of any blue color, the values less than 0 are not being plotted:
![2018-04-10_14-14-57](https://user-images.githubusercontent.com/1872600/38578809-05975820-3cd3-11e8-9875-fb23af8405a3.jpg)

It _**should**_ look like this (from NcWMS):
![2018-04-10_14-17-00](https://user-images.githubusercontent.com/1872600/38578849-206dcbf2-3cd3-11e8-8975-d8541f688b51.jpg)

This is an example request:
https://gamone.whoi.edu/wms/datasets/sgridtest?service=WMS&request=GetMap&version=1.1.1&layers=u&styles=filledcontours_jet&format=image/png&transparent=true&height=256&width=256&colorscalerange=-1.0,1.0&numcontours=20&logscale=false&srs=EPSG:3857&bbox=-7357522.594617926,5165920.119625353,-7200979.560689883,5322463.153553393

**Comment by rsignell-usgs** [comment]
This must be a new v2.0 problem, as the old sci-wms server didn't have this problem:
![2018-04-11_12-13-43](https://user-images.githubusercontent.com/1872600/38629357-d4e32ae2-3d81-11e8-9cc4-56fcf222294d.jpg)

http://sci-wms.whoi.edu/wms/demo

**Comment by kwilcox** [comment]
This isn't a negative values problem at all. You are viewing a different elevation which has many more fill values. I'll poke around to see why the default isn't the surface.

**Comment by rsignell-usgs** [comment]
None of the vertical layers for `u` have missing values like this, so I'm not sure you are right here.   Also very suspicious that there are no values less than 0.

**Comment by kwilcox** [comment]
This is the classic netcdf-4 breaking change that has since been reverted: https://github.com/Unidata/netcdf4-python/issues/761. The `_FillValue` for `u` is `0` so everything below it gets masked out. The tests pass when downgrading `netcdf4-python` to `1.2.8` in `sci-wms` so I'll do that until a new release is made.

**Comment by kwilcox** [comment]
I lied, there are multiple problems with downgrading to `netcdf4-python==1.2.8`... so we'll need to wait until `1.3.2` is released. :cry:

**Comment by kwilcox** [comment]
Just pushed a commit that makes `netcdf4-python>=1.4.0` and should solve this, let me know if you using the new image still has issues.
