### ISSUE TITLE
Provide projection support for EPSG:4326

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#15]
Currently only Web Mercator is supported.   We need to provide projection support for at least `EPSG:4326` so that other WMS clients like Godiva2 can work (see https://github.com/asascience-open/sci-wms/issues/109)

**Comment by brianmckenna** [comment]
Can work with pyproj handling the projection, as long as the CRS/SRS parameter is recognized by pyproj. COMT implementation assumes BBOX projections x/y in meters --- see [pyproj.Proj(x,y)](http://jswhit.github.io/pyproj/pyproj.Proj-class.html#__call__). This can easily be generalized though, dropping the inverse=True kwarg and instead always projecting the input coordinates to longitude/latitude. 

Be forewarned though, Godiva2 uses custom endpoints (returning JSON) to build the menu and layer details from NcWMS servers:

https://github.com/Unidata/ncWMS/blob/master/src/java/uk/ac/rdg/resc/ncwms/controller/AbstractMetadataController.java#L76-L116

https://github.com/Unidata/ncWMS/blob/master/web/js/server.js#L115-L132

Seamless integration with Godiva2 would be a multi-step process.

**Comment by rsignell-usgs** [comment]
@brianmckenna, thanks -- I did not know that godiva2 had custom JSON endpoints.  That's a bit disappointing.    Well, at least providing additional projections should make Sci-WMS accessible to other WMS clients, and an important step toward making it compatible with clients like godiva2.

**Comment by rsignell-usgs** [comment]
@kwilcox , can this be closed via #34 ?

**Comment by kwilcox** [comment]
Not quite, I'm going to look into Brians comment:

```
COMT implementation assumes BBOX projections x/y in meters --- see [pyproj.Proj(x,y)](http://jswhit.github.io/pyproj/pyproj.Proj-class.html#__call__). This can easily be generalized though, dropping the inverse=True kwarg and instead always projecting the input coordinates to longitude/latitude.
```

And write some visual tests.

**Comment by brianmckenna** [comment]
see https://github.com/sci-wms/sci-wms/blob/comt/sciwms/apps/wms/get_map.py#L70-L71

need a reference, EPSG4326 seems good, it's what the data is in

**Comment by kwilcox** [comment]
:+1: I opened #41 to address datasets that are not in WGS84 natively
