### ISSUE TITLE
Handle NaNs in data arrays

### ISSUE THREAD

**Issue by ayan-usgs** [sci-wms/sci-wms#16]
The salinity data at http://amb6400b.stccmop.org:8080/thredds/dodsC/model_data/forecast contains NaNs that seem to be causing matplotlib to raise RunTimeErrors when attempting a getMap request using either filledcontour or contour styles. The app should be able to deal with NaNs without throwing an error; ideally it should still respond with a map.

**Comment by rsignell-usgs** [comment]
@ayan-usgs , where do we stand with this issue?

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

It remains an outstanding task.

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

I can take a look at this today if you have no objections.

**Comment by ayan-usgs** [comment]
As a lot has changed since I created this issue. While this dataset is still having problems, `ValueError`s are being raised rather than `RunTimeError`s.

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

Regarding the dataset at http://amb6400b.stccmop.org:8080/thredds/dodsC/model_data/forecast.nc, I noticed that the `time` units are reported as `seconds` rather than "seconds since..." It also lists the `base_date` as as seconds since 2015-07-26 00:00:00 -8:00, which strikes me as implausible, since this dataset has been around prior to that. May I ask what the time `units` are? That seems to causing at least some of sciwms's heartburn.

**Comment by rsignell-usgs** [comment]
@ayan-usgs , okay, this is definitely NOT cf-compliant.   I'll contact the providers to see if we can get this fixed.

**Comment by rsignell-usgs** [comment]
@ayan-usgs , I thought this sounded familiar.   According to this thread https://github.com/ioos/registry/issues/69#issuecomment-76481434
we should be using this URL
http://amb6400b.stccmop.org:8080/thredds/dodsC/model_data/forecast.html
instead of
http://amb6400b.stccmop.org:8080/thredds/dodsC/model_data/forecast.nc.html
