### ISSUE TITLE
Add support for the GetMetadata requests as supported by ncWMS

### ISSUE THREAD

**Issue by kwilcox** [sci-wms/sci-wms#22]
For example, this returns the min/max of a layer at a certain time index and depth:
http://pdx.axiomalaska.com/ncWMS/wms?item=minmax&layers=NCSU_SABGOM_3/zeta&bbox=-9205029.8443555,2951384.085693,-8578857.7087305,3392884.3610068&time=2015-01-31T12:00:00Z&crs=EPSG:3857&width=50&height=50&request=GetMetadata

**Comment by akbstone** [comment]
This one includes depth (elevation): http://pdx.axiomalaska.com/ncWMS/wms?item=minmax&layers=PWS_L2_FCST/temp&bbox=88487.062216965,-3293749.4316437,229687.73037321,-3194191.9292913&elevation=-100&time=2015-03-27T06:00:00Z&crs=EPSG:3572&width=50&height=50&request=GetMetadata
