### ISSUE TITLE
Try adding `rasterized=True` to matplotlib calls

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#27]
Thanks to a tip from @ocefpaf, I was looking at http://www.astrobetter.com/slim-down-your-bloated-graphics/ and wondering:  would `rasterized=True` speed up matplotlib for sci-wms?

I'm thinking of calls like:
https://github.com/sci-wms/sci-wms/blob/fdc4fb23a79a2885ac2b1f162154cb1a5ae0c4ba/sciwms/libs/data/cgrid.py#L248

Or maybe it wouldn't have any effect on `pcolormesh`, but would be useful for WMS graphics that are contour line and vector plots?

If we already know the answer, fine, but if not, perhaps @ayan-usgs could test?

**Comment by kwilcox** [comment]
This would only have an effect if we were using vector images as response formats (pdf, etc.).  We already rasterize when creating a PNG.
