### ISSUE TITLE
Unable to display example data

### ISSUE THREAD

**Issue by cbcunc** [sci-wms/sci-wms#29]
From a pristine install of sci-wms/sci-wms main branch, an exception occurs and a pink layer appears when checking either the CGridTest or UGridTest example dataset in the client's OpenLayers widget as shown in https://gist.github.com/cbcunc/6794b7a22135368929ad . A pdb trace was applied to the offending line 1281 in sciwms/apps/wms/apps/views.py as shown in https://gist.github.com/cbcunc/3525c9898a3317e87c78 . The trace revealed the inability to stat a dataset at sciwms/apps/wms/topology/UGridTest.nc (or CGridTest.nc). The topology subdirectory is empty as shown in https://gist.github.com/cbcunc/bf8266888fe2541c0c93 . (This differs from the ASA version of sci-wms which does populate topology directory with UGridTest and CGridTest.) Running manage.py test completes with no failures or errors and 28 succesful tests in 153.222 seconds.

**Comment by rsignell-usgs** [comment]
@cbcunc, I seem to remember from our install that there was something missing in the instructions about setting up the topology cache.   Hopefully @kwilcox or @ayan-usgs will chime in here and get you going.  Once we figure it out, let's upgrade/fix the documentation so the next user doesn't have this problem!

**Comment by cbcunc** [comment]
Sounds great! We were just walking through the debugger and found that the correct URI for UGridTest was registered with the Django admin interface (sciwms/apps/wms/resources/201220109.nc). So we will await further instructions, Thank you for the feedback.

And we are glad to update documentation and have been planning to.

```
(Pdb) p Dataset.objects.values()
[{'keep_up_to_date': False, 'display_all_timesteps': False, 'title': u'CGrid Test dataset', 'abstract': u'CGrid Test data set for sci-wms', 'cache_last_updated': None, 'longitude_variable': u'', 'uri': u'/opt/sciwms/sci-wms/sciwms/apps/wms/resources/nasa_scb20111015.nc', 'latitude_variable': u'', 'json': None, 'test_layer': u'u,v', 'test_style': u'facets_average_jet_None_None_grid_False', u'id': 1, 'name': u'CGridTest'}, {'keep_up_to_date': False, 'display_all_timesteps': False, 'title': u'UGrid Test dataset', 'abstract': u'UGrid Test data set for sci-wms', 'cache_last_updated': None, 'longitude_variable': u'', 'uri': u'/opt/sciwms/sci-wms/sciwms/apps/wms/resources/201220109.nc', 'latitude_variable': u'', 'json': None, 'test_layer': u'u,v', 'test_style': u'facets_average_jet_None_None_node_False', u'id': 2, 'name': u'UGridTest'}]
(Pdb)
```

**Comment by rsignell-usgs** [comment]
@cbcunc,  can we arrange a screen-sharing session with @kwilcox and he can interactively debug the problems?  
Might be the most expedient way to figure out what is going on.   And let's make sure we fix or improve that documentation so that screen-sharing sessions are not necessary the next time!

**Comment by cbcunc** [comment]
I just saw your response to https://github.com/sci-wms/sci-wms/issues/28 so I think we'll give that a try and then if that works, there's no need to have a debug session for a checkin to master that wasn't expected to work.

**Comment by rsignell-usgs** [comment]
The problem was `Django=1.8` was installed, but `Django=1.7.5` was needed: https://github.com/ESIPFed/cf-dataset-curator/issues/1#issuecomment-91630829

**Comment by kwilcox** [comment]
Fixed in https://github.com/sci-wms/sci-wms/commit/95cc4acc0d70a0614d341a9df308b0353962d92e

**Comment by cbcunc** [comment]
Working procedure after release updated: https://gist.github.com/cbcunc/3df1aae5945e41764f7f#file-sciwms-server-config-v2-txt

**Comment by rsignell-usgs** [comment]
Could you add a `git remote -v` just before
https://gist.github.com/cbcunc/3df1aae5945e41764f7f#file-sciwms-server-config-v2-txt-L76
so we know where the sci-wms repo is?
I didn't see this info elsewhere

**Comment by cbcunc** [comment]
Not sure what you mean. The remote repo is specified on line 74 as https://github.com/sci-wms/sci-wms.git (which is what `git remote -v` outputs) and the local report is specified on line 73 as /opt/src/sci-wms.

**Comment by rsignell-usgs** [comment]
I thought you were listing the commands that you type and line 74 didn't look like a Unix command

**Comment by cbcunc** [comment]
Thanks. Fixed.
