### ISSUE TITLE
map client layers do not render

### ISSUE THREAD

**Issue by ayan-usgs** [sci-wms/sci-wms#31]
@kwilcox,

I was playing with the rel-2.0 branch of sci-wms and noticed that layers don't render when when is selected. It instead displays pink shadowing.

From preliminary sleuthing, this appears to be a consequence of the WMS requests not having a value for the LAYER parameter. This seems reasonable since the  `test_layer` column was removed from the `wms_dataset` table. However, it's unclear to me how you're envisioning the map client to work without the test layers if at all. Can you elaborate?

**Comment by kwilcox** [comment]
the branch isn't ready for "playing"... it isn't stable at all.  If you wanted to see the direction I was heading check out: https://github.com/axiom-data-science/sci-wms/tree/demo

**Comment by kwilcox** [comment]
Also, the map client is going away with rel-2.0. It has been replaced by a much better demo application that @daf merged from ASA's branch
