### ISSUE TITLE
Data outside specified color range should be transparent by default, and ideally specifiable

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#33]
What should we do with values that are outside the specified color range?  

NcWMS sets them to black:
![5-6-2015 3-49-31 pm](https://cloud.githubusercontent.com/assets/1872600/7502547/c387d89c-f40a-11e4-8fbe-d1c21ffc61b5.png)

But as the above image illustrates, black is not always what is most useful for the user. 

In many cases, transparent would be more valuable.   This would allow land and bathymetry to "show through" in the range of colors that are not of interest to the user. So I would argue that transparent would be a better choice than black.    

Transparency could be accomplished simply in sci-wms by using masked arrays http://stackoverflow.com/a/22672080

The worst choice would be to just extend the max color above and the min color below.   This is **very** misleading.

Ideally the user/client would allow specification of this behavior.

**Comment by brianmckenna** [comment]
Here's an example of transparent, currently the default behavior on comt.

I'm not a fan of the black, agree with it being misleading. But honestly I'm not a fan of the transparent, always felt like it was a bug I should fix.

How about implementing/sticking to greater than/less than as the top/bottom (left/right) on the scale. The color wouldn't change for extreme values, but the information is still presented to the user. 

![sciwms_necofs](https://cloud.githubusercontent.com/assets/207820/7503309/1eb7c470-f410-11e4-9ae2-1dfbfe2ac408.png)

**_changed the SSH range from 0-2m > 0-0.5m here to show effect**_

**Comment by rsignell-usgs** [comment]
I still like the transparent. If the user doesn't like that look they can expand the range!

**Comment by kwilcox** [comment]
@brianmckenna where are you setting the transparency?  It looks like the current behavior is what you mentioned "sticking to greater than/less than as the top/bottom": https://github.com/sci-wms/sci-wms/blob/comt/sciwms/apps/wms/matplotlib_handler.py#L174-L176

**Comment by kwilcox** [comment]
Transparent now by default
