### ISSUE TITLE
docker image for quick install of sci-wms

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#36]
Having gone through the pain of a sci-wms install on a system where apache and a host of other services were already running, and running into python environment issues, it seems that it would be really nice to have a docker image for sci-wms, where you could just specify a few things like the ports you want to use and be off and running.  

Something similar to the installation of the Birdhouse WPS service, perhaps?
http://birdhouse.readthedocs.org/en/latest/installation.html#using-birdhouse-with-docker

**Comment by ocefpaf** [comment]
:+1:

I understand that some sys-admins might want to have more control when installing `sci-wms`, but a docker image is a huge help for those who "just want it to work."
