### ISSUE TITLE
GetFeatureInfo requests need index files

### ISSUE THREAD

**Issue by ayan-usgs** [sci-wms/sci-wms#44]
GetFeatureInfo requests seem to require node and cell center index files that are subsequently used by the rtree package (https://github.com/sci-wms/sci-wms/blob/rel-2.0/wms/views.py#L348-L387). It appears that the `build_from_nc` function at https://github.com/sci-wms/sci-wms/blob/master/sciwms/libs/data/build_tree.py#L26-L63 would create the necessary files, but the function doesn't appear to be hooked-up to anything. A mechanism should be in place to generate the requisite index files.

**Comment by ayan-usgs** [comment]
@kwilcox,

Is this issue an apt assessment of the problem?

**Comment by kwilcox** [comment]
I have it working for UGRID and will submit a pull request soon: https://github.com/axiom-data-science/sci-wms/commit/8f00238f4a481d1d3fa0f77a1cbebed85a68b384

**Comment by brianmckenna** [comment]
this was working in COMT branch

https://github.com/sci-wms/sci-wms/blob/comt/sciwms/libs/data/caching.py#L77-L89
https://github.com/sci-wms/sci-wms/blob/comt/sciwms/libs/data/build_tree.py#L37-L50

**Comment by kwilcox** [comment]
Pulled most of the code from there.  We still only index nodes.  Need to implement a faces index eventually.
