### ISSUE TITLE
Support datasets with multiple variables with standard_name = time when rendering a getmap request

### ISSUE THREAD

**Issue by ayan-usgs** [sci-wms/sci-wms#45]
In datasets with multiple variables with `standard_name = time`, the correct time variable needs to be selected when rendering a getmap request. The current code grabs the first time variable that is found.

**Comment by rsignell-usgs** [comment]
Can't we use the variable that is listed in the coordinates attribute?

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

That's essentially what I have implemented in the latest pull request.

**Comment by kwilcox** [comment]
FYI, I've ported this to UGRID as well, so we should be good going forward in both cases!
