### ISSUE TITLE
Incorporate plotting optimizations from testbed branch

### ISSUE THREAD

**Issue by kwilcox** [sci-wms/sci-wms#5]
From the comt branch

**Comment by rsignell-usgs** [comment]
According to @brianmckenna, improvements were made to the plotting routines to speed up the generation of WMS images.   This included replacing `basemap` with `pyproj`, and possible other enhancements.

**Comment by rsignell-usgs** [comment]
@kwilcox, closed without comment?
Addressed in PR?
Will-not-fix?
tests showing comparable performance?

**Comment by kwilcox** [comment]
It's the same code, I incorporated it 100%.

**Comment by rsignell-usgs** [comment]
In which PR?

**Comment by kwilcox** [comment]
3321437397aa56a92d45dce39bbb343bf56d8940
