### ISSUE TITLE
Scale vectors based on size of bbox in quiver responses

### ISSUE THREAD

**Issue by kwilcox** [sci-wms/sci-wms#51]
Currently the vectors are autoscaled, and that doesn't look great when tiling.

http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.quiver

See scale, scale_units

**Comment by acrosby** [comment]
To get consistent vectors scales when tiling you need to explicitly set the scale and units when you call quiver for each tile.

You probably need to know the following to calculate the scale:
- Absolute range (min and max) of the data across all of the tiles-won't know this probably.
  - Should probably set sane defaults based on units/parameter???
  - Maybe add WMS parameter to override our sane defaults in the case of data is wacky?
- dpi/size of bbox/tile
- desired size of arrow for a given data value in your given units
  - this may tie into the resolution or geographic spacing of the data

http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.quiver

_scale_: [ None | float ]
- Data units per arrow length unit, e.g., m/s per plot width; a smaller scale parameter makes the arrow longer. If None, a simple autoscaling algorithm is used, based on the average vector length and the number of vectors. The arrow length unit is given by the scale_units parameter

_scale_units_: None, or any of the units options.
- For example, if scale_units is ‘inches’, scale is 2.0, and (u,v) = (1,0), then the vector will be 0.5 inches long. If scale_units is ‘width’, then the vector will be half the width of the axes.
- If scale_units is ‘x’ then the vector will be 0.5 x-axis units. To plot vectors in the x-y plane, with u and v having the same units as x and y, use “angles=’xy’, scale_units=’xy’, scale=1”.

**Comment by acrosby** [comment]
i guess quiver is mostly for currents and possibly wave dir, and barbs are for winds (because of exactly this problem)

so it might be pretty easy to have a general rule based on the size of the arrow you want for say a data value of 5, and the spacing of the data

**Comment by rsignell-usgs** [comment]
@ayan-usgs , can you take a look at this?    We need to figure out a reasonable scale based on the min/max, and then specify that for all the plot commands.  We don't wan't autoscaling because it will be different on each tile.

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

Yep. I can look into this.

**Comment by kwilcox** [comment]
Fixed via #58
