### ISSUE TITLE
create a summary of WMS extensions, like ncwms

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#56]
I discovered this list of ncWMS extensions:
http://www.resc.rdg.ac.uk/trac/ncWMS/wiki/WmsExtensions

and was thinking we should have a table like this that lists our WMS extensions.  Or perhaps we already do?

**Comment by kwilcox** [comment]
http://sci-wms.github.io/sci-wms/docs/advanced.html#wms-extensions

**Comment by rsignell-usgs** [comment]
@kwilcox , looks great!   Thanks Kyle!
