### ISSUE TITLE
Use pyugrid when processing ugrids

### ISSUE THREAD

**Issue by kwilcox** [sci-wms/sci-wms#6]

**Comment by ayan-usgs** [comment]
Here's the tactical approach I going to take with this:
- Get topology caching with pyugrid -- Working (I think)
- Get getCapabilities working with the new topology
- Get WMS working with pyugrid.

My intent to get sci-wms working with datasets that are UGRID compliant, while files that are not compliant won't work. I don't see a compelling reason to maintain comparability with any netCDF dataset at this juncture as things are going to change pretty significantly for this task, and even more so when pysgrid is written and incorporated into sci-wms.

**Comment by rsignell-usgs** [comment]
@ayan-usgs, agreed.  We don't need to support non-`UGRID` files.  Once providers see how cool this stuff is, they will want their model results to be included, and we can help them `UGRID`-ize their data.  We just did this for the RENCI guys: https://github.com/rsignell-usgs/kennedy/issues/1

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

I've the getMap service working for the most part. The image below was generated from a getMap request (/wms/datasets/UGRIDConform/?REQUEST=getmap&layers=min_temp&bbox=-13823397.0627,5785041.63881,-13724756.7763,5842125.54119&height=800&width=1200&styles=filledcontours_maximum_jet_None_None_node_False&time=1990-01-01) for the min_temp variable from the dataset at http://amb6400b.stccmop.org:8080/thredds/dodsC/model_data/forecast. What are your thoughts on the image? Does it bare any resemblance to what you where expecting?

![forecast](https://cloud.githubusercontent.com/assets/1903370/6696574/5a3e8422-ccb8-11e4-8d26-b172e8999fcd.png)

**Comment by rsignell-usgs** [comment]
@ayan-usgs , that's awesome!   The geometry looks right -- not sure about the values because minimum_temperature is a variable I don't think about very often.     How about a plot of salinity for this same dataset?    That I might have some more intuition about!  ;-)

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

Hmm... the salinity data seems to be giving the getMap service problems. I'll post an image of the response once I have the kinks worked out.

**Comment by rsignell-usgs** [comment]
Are you specifying `ELEVATION=1` in the request?  
In sci-wms, the ELEVATION is actually the layer number.  
http://asascience-open.github.io/sci-wms/using.html#sci-wms-getmap

**Comment by ayan-usgs** [comment]
I didn't think it was necessary as an elevation of 0 is used if `elevation` isn't explicitly specified in the request. However, upon seeing your comment, I tried setting `elevation=1` and got the following matplotlib errors: `invalid value encountered in greater` and `invalid value encountered in less`; these were the same errors I encountered without explicitly specifying `elevation`.

My current hypothesis is that it's the ~4600 NaNs in a given avg salt array that is causing matplotlib's to vomit.

**Comment by rsignell-usgs** [comment]
Andrew, want to try another dataset that I'm more familiar with?  How about this one:
http://fvcom.smast.umassd.edu:8080/thredds/forecasts.html?dataset=gom3_nocache

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

The GOM3 seems to be more cooperative. Here's a PNG I got from a getMap request (/wms/datasets/UGridForcasts/?REQUEST=getmap&layers=salinity&elevation=1&bbox=-8425141.49979,4201524.42149,-6328601.20898,5803768.78817&height=800&width=1200&styles=filledcontours_average_jet_None_None_grid_False&time=1976-07-07T01:00:00Z).

Does that image look anything like what you are expecting?

![necofs_gom3_forecast](https://cloud.githubusercontent.com/assets/1903370/6717775/e42a23f2-cd7c-11e4-8a07-f868a9773b41.png)

**Comment by rsignell-usgs** [comment]
@ayan-usgs , yes, that looks great!
