### ISSUE TITLE
Add vectorstep option

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#60]
@ayan-usgs, while you are fresh off the addition of `vectorscale`, could we also add the `vectorstep` that John Maurer (@pacioos) was looking for here?
http://sourceforge.net/p/ncwms/mailman/message/31828123/

For SGRID and RGRID, of course it's straightforward.  We use an approach like

```
isub=vectorstep
data[::isub,::isub]
```

and for UGRID we could use an approach where we randomly drop vectors like this:

```
# instead of plotting all points...
plt.quiver(lonc,latc,u,v,scale=20)

# instead, we find subsampled velocity points in bounding box:
ind = np.argwhere((lonc >= ax[0]) & (lonc <= ax[1]) & (latc >= ax[2]) & (latc <= ax[3]))
np.random.shuffle(ind)
Nvec = int(len(ind) / isub)
idv = ind[:Nvec]
Q = plt.quiver(lonc[idv],latc[idv],u[idv],v[idv],scale=20)
```

As in the real example shown in this notebook: http://nbviewer.ipython.org/gist/rsignell-usgs/7aaa1563081ada017e0a

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

Would it be possible to to have `standard_name = time` added to the time variables in the http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc dataset? I know it won't look exactly the same because vectors are randomly dropped, but I'm trying the verify the overall effect. The missing `standard_name` is causing be some grief.

Similarly useful with be the addtion of "UGrid` to the dataset conventions.

Would these changes be possible?

**Comment by rsignell-usgs** [comment]
@ayan-usgs, hmm, it would have been possible, but it looks like I can no longer ssh into that machine.

I'll see what's going on.

**Comment by ayan-usgs** [comment]
Seems to be working with SGrid datasets.
![sgrid_coawst_vectorstep_5](https://cloud.githubusercontent.com/assets/1903370/8836810/ac43fbce-3088-11e5-8953-3e883730966e.png)

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

How are things going with SSH problem and the FVCOM dataset?

**Comment by rsignell-usgs** [comment]
@ayan-usgs , this is super cool!    I contacted the SMAST folks and they said they would get me access again, but didn't say when, do I downloaded just 1 step:

```
ncks -d time,0 http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_FVCOM_OCEAN_MASSBAY_FORECAST.nc massbay_1step.nc
```

and then created this little `NcML` file:

```
 <netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2"
      location="./massbay_1step.nc">
      <remove type="attribute" name="cdm_data_type"/>
      <attribute name="featureType" value="ugrid"/>
      <attribute name="Conventions" value="CF-1.4, UGRID-0.9"/>
      <variable name="time">
      <attribute name="standard_name" value="time"/>
      </variable>
   </netcdf>
```

which you can access here:
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/rsignell/models/fvcom/1step.ncml.html

Let me know if you need any more changes -- it should be easy now!  :smile_cat:

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

Thanks for changing the those attributes. For your viewing pleasure, I would like to present these two images from the dataset, with a `vectorstep` of 2 and 10 respectively.

`vectorstep=2`

![fvcom_1step_vectorstep_2](https://cloud.githubusercontent.com/assets/1903370/8877748/a94a962a-31ec-11e5-8181-e0f96e15a280.png)

`vectorstep=10`
![fvcom_1step_vectorstep_10](https://cloud.githubusercontent.com/assets/1903370/8877749/ade66cd6-31ec-11e5-8b6f-fe7991fd207e.png)

**Comment by ayan-usgs** [comment]
I should be ready to submit a PR this afternoon.

**Comment by rsignell-usgs** [comment]
@ayan-usgs, super awesome!!!!

**Comment by rsignell-usgs** [comment]
@kwilcox , I should raise an issue on https://github.com/USGS-CMG/usgs-cmg-portal/issues so that CMG portal users can enable these new params, right?

**Comment by kwilcox** [comment]
Awesome!

**Comment by rsignell-usgs** [comment]
@hetland just walked into my office and said we should use  "Poisson Disk" for sampling "uniformly"  http://bost.ocks.org/mike/algorithms/ 
would work for unstructured and structured.  Only question is how long it takes.  @ayan-usgs would you be interested in taking a look?

**Comment by ayan-usgs** [comment]
@rsignell-usgs and @hetland,

Sure, I can take a look at it. I'll come up with an estimate of how much effort it would take to implement sample using a Poisson Disk. We can decide whether or not to proceed from there.

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

I'm thinking this would take a good amount of effort and thought; a conservative time estimate would be about four days. Should I proceed? If so, I'll create a new issue.

Personally, I'm intrigued by the prospect the implementing this and certainly would enjoy doing so.

**Comment by rsignell-usgs** [comment]
@ayan-usgs , how many days of developer time would you say you have left on this project?

**Comment by hetland** [comment]
@ayan-usgs I expect your 4 day estimate is about right. One motivation for
doing this project despite the non-trivial time investment is that it is a
pretty generic problem, so if you implement it in a stand-alone way, it
could be used by many many other people.

On Mon, Jul 27, 2015 at 10:29 AM, Rich Signell notifications@github.com
wrote:

> @ayan-usgs https://github.com/ayan-usgs , how many days of developer
> time would you say you have left on this project?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sci-wms/sci-wms/issues/60#issuecomment-125225663.

## 

Prof. Rob Hetland
Texas A&M Univ.  –  Dept. of Oceanography
http://pong.tamu.edu/~rob

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

After speaking with our budget guru, I'd estimate about 24 developer days.

**Comment by rsignell-usgs** [comment]
hmmm, I guess unfortunately we should put this idea on hold then.   There are other things that are higher priority.
