### ISSUE TITLE
Docker Build Fails: No lapack/blas resources found

### ISSUE THREAD

**Issue by metanomy** [sci-wms/sci-wms#67]
Docker build fails: numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

**Comment by kwilcox** [comment]
@metanomy https://github.com/sci-wms/sci-wms/pull/69 most likely fixes your issue. I'm running out the door but will test more later this week

**Comment by pauljesseturner** [comment]
I had a similar problem with lapack etc. and this current docker build is working nicely for me including the Leaf demo with ugrid data (selfe) I added from our thredds server. I just need to figure out how to handle time and dry nodes which I assume are missing data or nans.

Really nice work you guys are doing, thx.

--Paul

Paul Turner
OHSU/CMOP

----- Original Message -----
