### ISSUE TITLE
Docker Build

### ISSUE THREAD

**Issue by metanomy** [sci-wms/sci-wms#70]
Docker builds, but Leaflet demo map doesn't seem to load

![image](https://cloud.githubusercontent.com/assets/11446338/9209139/06d7a6e8-4043-11e5-8da2-88f640c896f7.png)

**Comment by kwilcox** [comment]
The Demo map uses the name of the dataset as a variable name, so it needs to be a valid JS variable name (no spaces or dashes). The default slug method was using dashes.  I just sent a PR to fix (https://github.com/sci-wms/sci-wms/pull/71). You can update the dataset name/slug in the Django Admin console to use an underscore for now!

**Comment by metanomy** [comment]
Underscore set, and now the GetCapabilities functions: http://162.223.15.109:7002/wms/datasets/wfs_fvcom?REQUEST=GetCapabilities.

Leaflet still isn't working, but I need to check the Docker image build log to make sure something didn't happen along the way.

Strangely can't seem to get TerriaJS to recognize it (try it yourself: tampabaymap.org, select "Add Data", and paste in this url: http://162.223.15.109:7002/wms/datasets/wfs_fvcom). This could be a CORS issue

**Comment by daf** [comment]
@metanomy I tried your steps, I see a bunch of 500s in the inspector/network tab coming back from the requests to sci-wms via the proxy.  Maybe the proxy isn't receiving/converting the arguments correctly, or it can't see the sci-wms server internally?

**Comment by metanomy** [comment]
Most likely my ignorance with varnish. It might be easier to configure gunicorn to handle CORS and not proxy with varnish.

For your edification, here is the varnish config settings:

#sci-wms
backend sciwms {
    .host = "sci-wms";
    .port = "7002";
}

sub vcl_recv {
.........
    if (req.url ~ "^/sci-wms/") {
        set req.backend = sciwms;
    set req.url = regsub(req.url, "^/sci-wms/", "/");
    } else {
        set req.backend = default;
    }

**Comment by metanomy** [comment]
Latest source resolves Docker build issues.
