### ISSUE TITLE
Requests including requests with timezones causing errors

### ISSUE THREAD

**Issue by ayan-usgs** [sci-wms/sci-wms#76]
Issue related to https://github.com/USGS-CMG/usgs-cmg-portal/issues/99 and https://github.com/Unidata/netcdf4-python/issues/357.

Also per netCDF4 documentation:

```
date2num(dates, units, calendar='standard')
source code 
Return numeric time values given datetime objects. The units of the numeric time values are described by the units argument and the calendar keyword. The datetime objects must be in UTC with no time-zone offset. If there is a time-zone offset in units, it will be applied to the returned numeric values.

Like the matplotlib date2num function, except that it allows for different units and calendars. Behaves the same if units = 'days since 0001-01-01 00:00:00' and calendar = 'proleptic_gregorian'.
```

**Comment by ayan-usgs** [comment]
I've added a line to ensure that the datetime is timezone naive with the assumption that the request datetime is in UTC. The WMS specification doesn't provide for any other timezones.

@kwilcox and @rsignell-usgs: I'm leaning towards requiring a `Z` suffix for the `TIME` parameter and raising an exception otherwise. WMS requires the suffix, but sci-wms doesn't. Do you have any thoughts regarding this?

**Comment by rsignell-usgs** [comment]
Yes, I'm in favor.

**Comment by kwilcox** [comment]
Fixed in master

**Comment by rsignell-usgs** [comment]
Fixed in https://github.com/sci-wms/sci-wms/commit/7dfad42d0d788cf1ba131597d9c040792b465ca1
