### ISSUE TITLE
Docement resources for running a Django/WSGI production application

### ISSUE THREAD

**Issue by kwilcox** [sci-wms/sci-wms#8]

**Comment by rsignell-usgs** [comment]
@cbcunc, could you please post the issues you discovered when trying to install?  
It would be a helpful to know where the problems are.

We were able to get sci-wms installed, but it took some hand-holding from @kwilcox and we want to improve upon that process.  :worried:

**Comment by cbcunc** [comment]
@rsignell-usgs, my issues were all with the [ASA comt_testbed branch](https://github.com/asascience-open/sci-wms/tree/comt_testbed). This is a fork is a fresh start. Let me run through the installation with this branch, and then I'll post those issues, if any. Thanks!
