### ISSUE TITLE
Implement `facets` and `pcolor` on SGRID and UGRID

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#86]
If I look at the example [GetCaps from a UGRID dataset](http://sci-wms.whoi.edu/wms/datasets/ugridtest?REQUEST=GetCapabilities), I see that there is a layer with name `elev` and that `facets_jet` is one of the available styles:

```
            <Layer opaque="0" queryable="1">
                <Name>elev</Name>
                <Title>sea_surface_height_above_sea_level</Title>
                <Abstract></Abstract>
                <SRS>EPSG:3857</SRS>
                <LatLonBoundingBox maxx="46.3841552734" maxy="-123.29158783" minx="46.0292739868" miny="-124.177688599" />
                <BoundingBox SRS="EPSG:4326" maxx="46.3841552734" maxy="-123.29158783" minx="46.0292739868" miny="-124.177688599" />
                <Dimension name="time" units="ISO8601" />

                    <Extent name="time">2015-04-27T16:15:00/2015-04-27T18:45:00/PT15M</Extent>

...
                <Style>
                    <Name>filledcontours_jet</Name>
                    <Title>filledcontours_jet</Title>
                    <Abstract></Abstract>
                    <LegendURL height="80" width="50">
                        <Format>image/png</Format>
                    </LegendURL>
                </Style>
...
                <Style>
                    <Name>facets_jet</Name>
                    <Title>facets_jet</Title>
                    <Abstract></Abstract>
                    <LegendURL height="80" width="50">
                        <Format>image/png</Format>
                    </LegendURL>
                </Style>

            </Layer>
```

If I try using `filledcontours_jet` GetMap request, it works:
http://sci-wms.whoi.edu/wms/datasets/ugridtest?service=WMS&request=GetMap&version=1.1.1&layers=elev&styles=filledcontours_jet&format=image/png&transparent=true&height=256&width=256&colorscalerange=0,1&srs=EPSG:3857&bbox=-13775786.985667603,5792092.255337515,-13697515.468703583,5870363.772301538

But if I try switching the style on the above request to `facets_jet`, the GetMap request fails:
http://sci-wms.whoi.edu/wms/datasets/ugridtest?service=WMS&request=GetMap&version=1.1.1&layers=elev&styles=facets_jet&format=image/png&transparent=true&height=256&width=256&colorscalerange=0,1&srs=EPSG:3857&bbox=-13775786.985667603,5792092.255337515,-13697515.468703583,5870363.772301538

Giving the error: `Image type "facets" is not supported.`

Which seems odd, since we didn't request a "facets" image type.

**Comment by kwilcox** [comment]
The "new-school" sci-wms has never supported `facets` or `pcolor` for `UGRID` datasets. It is something we need to implement.  You can remove it from the GetCaps by removing the style from that layer in the Django admin interface.

**Comment by kwilcox** [comment]
Both SGRID and UGRID have a `pcolor` image_type now.  If you can let me know the different between pcolor and what facets should do, I'll reopen!

**Comment by rsignell-usgs** [comment]
Well, in matlab, we had 3 types of shading for grids: "interp" (interpolated color over the cell faces), "flat" (uniform color on the cell faces), and "faceted" (uniform color on the cell faces, but with black lines on the cell edges so you could see the grid cells clearly).

**Comment by ocefpaf** [comment]
In matplotlib the `shading="faceted"` is deprecated in favor of something like `edgecolors='k', linewidths=2` to give the users more control over the cells contour.

The real question is: how to define the proper bounds to get the data in the center of the cell? If the netCDF file has bounds, which is a rare thing, we can just use the bounds to pcolor.  If no bounds exist we must compute them.  Because pcoloring against x, y, data will not center the cell.

In matlab we had the pcolorjw that shifted things and plotted half cells at the borders.  In Python we can do better by implementing something similar to iris `guess_bounds()` method and use pcolor properly.

(See: https://ocefpaf.github.io/python4oceanographers/blog/2015/01/05/pcolor/)

**Comment by rsignell-usgs** [comment]
@ocefpaf, is this the relevant code?
https://github.com/SciTools/iris/blob/master/lib/iris/coords.py#L1056-L1086

**Comment by ocefpaf** [comment]
It is actually `self._guess_bounds(bound_position)`, must love when a public method just points you to a private method without a reason :wink: 

See: http://nbviewer.ipython.org/gist/ocefpaf/0fcade4f7f8b3c58c5fa
