### ISSUE TITLE
style with hatching

### ISSUE THREAD

**Issue by PBrockmann** [sci-wms/sci-wms#92]
A wish about having the possibility to get a WMS layer with hatching style.

It would be really useful to reproduce as "slippy maps", figures from IPCC such as https://www.ipcc.ch/publications_and_data/ar4/wg1/en/figure-10-9.html

A patch to the pydap code allowed me to experiment this feature few years ago. Read the threat from https://groups.google.com/forum/#!topic/pydap/yUs7tBN7O60
![pydap_wms_uncertainties](https://cloud.githubusercontent.com/assets/5402758/10818152/8f529160-7e3f-11e5-8318-f824aa86783b.png)

I think this hatch keyword is only avalaible from the contourf method so could be made visible for the sci-wms parameter STYLE when filledcontours is used.
See http://matplotlib.org/examples/pylab_examples/contourf_hatching.html

Let me know if any interest in that feature.

**Comment by kwilcox** [comment]
@PBrockmann I like it!  I'll take a quick look this week.

**Comment by kwilcox** [comment]
The first thing that comes to mind is two new styles:
- `colorhatch_cubehelix` uses a colormap and a  default set of hatches
- `hatch_filler` uses just the hatches to fill

@PBrockmann Would you need to be able to define the hatches manually, or can there be a default set of hatches?  The default set is much easier, because it can always match the NUMCONTOURS parameter. If we allow the user to define the hatches, there may be a mismatch.

**Comment by kwilcox** [comment]
I've got a working implementation on SGRIDs. `matplotlib` doesn't support hashing triangular grids so we can't support UGRIDs.

`styles=filledhatches_cubehelix`

![test_sgrid_legend_filledhatches](https://cloud.githubusercontent.com/assets/13939/10827806/391365d8-7e47-11e5-9b8c-a383b8aaa5f0.png)

![test_sgrid_legend_filledhatches_horizontal](https://cloud.githubusercontent.com/assets/13939/10827941/044edd7c-7e48-11e5-889e-4f7d9c84538f.png)

![test_sgrid_colorhatches](https://cloud.githubusercontent.com/assets/13939/10827873/83f3d506-7e47-11e5-8dec-ecf08b8f177e.png)

`styles=hatches_cubehelix` (the colormap is ignored)

![test_sgrid_legend_hatches](https://cloud.githubusercontent.com/assets/13939/10827786/19b17676-7e47-11e5-9954-2c72be03e563.png)

![test_sgrid_hatches](https://cloud.githubusercontent.com/assets/13939/10827876/8e016810-7e47-11e5-9473-377443d104f1.png)

**Comment by PBrockmann** [comment]
@kwilcox: Would you need to be able to define the hatches manually, or can there be a default set of hatches? The default set is much easier, because it can always match the NUMCONTOURS parameter
--> Yes you are right. Would be easier but would be nice if the user can choose the pattern (just as a character as said in matplotlib haching doc).
The first thing I imagine to do with that feature is to overlay a layer that would come from a variable of a netcdf file and that would have values 1 or missing. In this case, hatching would be plotted where values are 1 and so only with one hatching style.
