### ISSUE TITLE
Making getmap requests from TerriaJS work

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#97]
This is an example of a getMap request from TerriaJS to sci-wms, that gives a 500 error:

http://sci-wms.whoi.edu/wms/datasets/coawst?time=2012-06-25T06%3A00%3A00Z&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=Hwave&bbox=-8453323.832114212%2C2504688.542848654%2C-8140237.7642581295%2C2817774.6107047386&width=256&height=256

Do you see the problem?

**Comment by kwilcox** [comment]
Needs something in the styles parameter

http://sci-wms.whoi.edu/wms/datasets/coawst?time=2012-06-25T06%3A00%3A00Z&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=filledcontours_jet&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=Hwave&bbox=-8453323.832114212%2C2504688.542848654%2C-8140237.7642581295%2C2817774.6107047386&width=256&height=256

Don't remember the WMS spec on this, will check.

**Comment by rsignell-usgs** [comment]
I'm hoping that this is like the time and elevation parameters, that if unspecified, it will choose a default.

**Comment by rsignell-usgs** [comment]
I would argue that the default should be `styles=filledcontours_jet` with `NUMCONTOURS=50`

**Comment by kwilcox** [comment]
WMS 1.1.1

```
A client may request the default Style using a null value (as in "STYLES="). If several
layers are requested with a mixture of named and default styles, the STYLES parameter
includes null values between commas (as in "STYLES=style1,,style2,,"). If all layers are
to be shown using the default style, either the form "STYLES=" or "STYLES=,,," is
valid.
```

I'll assign a default style to each layer and make it configurable

**Comment by rsignell-usgs** [comment]
Awesome.   Thanks!

**Comment by kwilcox** [comment]
![selection_079](https://cloud.githubusercontent.com/assets/13939/10852152/a0661276-7f05-11e5-9d21-dfbc32208f48.png)
