### ISSUE TITLE
blank tile requests?

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#98]
As mentioned here
https://github.com/sci-wms/sci-wms/issues/96#issuecomment-152520047
we seem to have some blank tile requests.   I tried backing off on the zoom, and I saw 8 getMap requests, but only of 3 them are returning images with data on them.  The other 5 are blank.   Is this unavoidable?

![2015-10-30_9-18-16](https://cloud.githubusercontent.com/assets/1872600/10846636/7b9f30da-7ee7-11e5-8410-b19599c1311c.png)

**Comment by kwilcox** [comment]
This is how all JS clients work (OpenLayers, Leaflet, etc.). its so if the user pans slightly it doesn't force a reload on any tiles. Not something solvable in sci-wms.

**Comment by rsignell-usgs** [comment]
Ok.  Makes sense. Thanks for the explanation.
